modifyLineBreaks:
    textWrapOptions:
        blocksFollow:
           other: |-
             (?x)\\item
                 |
                 \\ifnum
                 |
                 \\mycommand\{
                 |
                 \\\[
                 |
                 \\\]
                 |
                 \[
        blocksEndBefore:
           other: |-
             (?x)\\\[
                 |
                    \\end\{
                 |
                    \\fi
                 | 
                    \}
                 | 
                    \]
